export default interface User {
    userID: number,
    name: string,
    lastName: string,
    email: string,
    password: string,
    birthdate: string,
    image: string,
    levelBonus: string,
    levelID: number,
    levelName: string,
    levelPercentage: number,
    placeID: number,
    points: number,
    roleDescription: string,
    roleID: number,
    roleName: string,
    type: string, 
    stripe_id: string,
    stripe_connect_id: string
}